FROM node:alpine

WORKDIR /app

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY package.json ./

COPY . .

RUN npm install
RUN npm rebuild node-sass

EXPOSE 3000

CMD [ "yarn", "server-start" ]
